`groupReport` <- 
function(dataMatrix, gAList, topCat=10, methodOfCluster=c('mds', 'sort'), matrixOfHeatmap=NULL, clusterTable=c('geneNum', 'pvalue', NULL), catTerm=TRUE, 
		fileName = "multiConceptsGenes.html", title='Multigroup Genes Concepts Analysis', catType=c('GO', 'KEGG', 'DOLite','Unknown'), reverseOfCluster=FALSE,  colorValueColumn = NULL, 
		annLib=c('org.Hs.eg.db', 'org.Rn.eg.db', 'org.Mm.eg.db', 'org.Dm.eg.db'), ...) { 
	catType <-match.arg(catType)
	annLib <- match.arg(annLib)
	
	showCats <- c(1:topCat)
	
	if (!is.null(colorValueColumn) & (length(colorValueColumn) > 1) & (length(colorValueColumn) != length(gAList))) stop('Specified colorValueColumns can not match the given gAList! Aborting ...')
	
	if (length(colorValueColumn) == 1) colorValueColumn <- rep(colorValueColumn, length(gAList))
	
	if (is.matrix(dataMatrix) | is.data.frame(dataMatrix) | is.vector(dataMatrix)) {
		dataMatrix <- as.matrix(dataMatrix)
		if ((NA %in% rownames(dataMatrix)) | is.null(rownames(dataMatrix))) print('Warning: NA or NULL might be in rownames of dataMatrix!')
		if ((NA %in% colnames(dataMatrix)) | is.null(colnames(dataMatrix))) print('Warning: NA or NULL might be in colnames of dataMatrix!')
	} else stop('Input is not a valid matrix!')
	
	HTwrap <- function(x, tag = "TD", scripts=NULL) {
        if (is.null(scripts)) return(paste("<", tag, ">", x, "</", tag, ">", sep = ""))
		else return(paste("<", tag, ' ', scripts, ">", x, "</", tag, ">", sep = ""))
    }

    if (!is.null(clusterTable) & !is.null(matrixOfHeatmap)) {
		if (clusterTable == 'geneNum') {
			if (is.numeric(dataMatrix)) {
				baseM <- dataMatrix[1:(dim(dataMatrix)[1]-1),]
			}
			else stop('The input Matrix is not numeric!')
		} else {
			baseM <- matrixOfHeatmap
		}

		if (methodOfCluster == 'mds') {
			distBaseM <- as.matrix(dist(baseM, method = "euclidean", upper=TRUE))
			distBaseM[distBaseM < 1e-6] <- 1e-6
			diag(distBaseM) <- 0
			clusterResult <- isoMDS(distBaseM, k=1)$points
			clusterOrder <- rownames(clusterResult)[order(clusterResult, decreasing=reverseOfCluster)]
			originalIndexMatrix <- originalIndexMatrix[clusterOrder,]
			matrixOfHeatmap <- matrixOfHeatmap[clusterOrder,]
			tempM <- dataMatrix[c(clusterOrder, rownames(dataMatrix)[dim(dataMatrix)[1]]),]
			dataMatrix <- tempM
		} else {
			clusterOrder <- sort(rownames(baseM), ...)
			tempM <- dataMatrix[c(clusterOrder, rownames(dataMatrix)[dim(dataMatrix)[1]]),]
			dataMatrix <- tempM
		}
	}
 
    indexM <- which(dataMatrix > 0, arr.ind=TRUE)
    if (catType != 'Unknown') {
		tableNames <- c('Concepts-Genes Table', paste('Group', colnames(dataMatrix), 'Concepts-Gene network'), gsub('Genes / Group :: NA and ', replacement='', 
							paste('Genes in', rownames(indexM)[1:dim(indexM)[1]], '::', getCategoryTerms(rownames(indexM)[1:dim(indexM)[1]], catType=catType, missing='keep'), 'and Group', colnames(dataMatrix)[indexM[1:dim(indexM)[1],2]])))
	} else {
		tableNames <- c('Concepts-Genes Table', paste('Group', colnames(dataMatrix), 'Concepts-Gene network'), gsub('Genes / Group and ', replacement='', 
							paste('Genes in', rownames(indexM)[1:dim(indexM)[1]], 'and Group', colnames(dataMatrix)[indexM[1:dim(indexM)[1],2]])))
	}
    attr <- c(catType, rep('Pictures', dim(dataMatrix)[2]), rep('Entrez', dim(indexM)[1]))
	outFile <- file(fileName, "w")
	cat('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">', file = outFile, sep = "\n")
    cat("<html  xmlns='http://www.w3.org/1999/xhtml' xml:lang='en' lang='en'>", HTwrap(HTwrap(title, tag = "title"), tag = "head"), "<body bgcolor=\"#FFFFcc\">", file = outFile, sep = "\n")
    
    if (!missing(title)) cat("<center><H1 align=\"center\">", title, " </H1></center>\n", file = outFile, sep = "\n")
	cat('</body>', "</html>", sep = "\n", file = outFile)
	
	cat('<H1><font face="courier" size="4"><a name="h-0">Multigroup Genes Concepts Analysis</a></font></H1>\n
		<font face="courier" size="1">Generated by Bioconductor package <a HREF="http://www.bioconductor.org/packages/release/bioc/html/GeneAnswers.html">GeneAnswers</a></font>\n<p>  </p>',file = outFile, sep = "")
	
	for (i in 1:(1+dim(dataMatrix)[2])) {
		cat(paste('<li><font face="courier" size="2"><a href="', paste('#h-', i, sep=''), '">', sep=''), tableNames[i], '</a></font>\n<p></p>\n',file = outFile, sep = "")
	}
	for (i in 1:length(tableNames)) {
		if (attr[i] != 'Pictures') {
			if (attr[i] == 'Entrez') {
				a <- i - 1 - dim(dataMatrix)[2]
				if (indexM[a,1] == dim(dataMatrix)[1]){
					# generate all genes table
					temp <- as.matrix(getGeneInput(gAList[[indexM[a,2]]]))
					rownames(temp) <- temp[,1]
                    if (dim(temp)[1] > 1) {
						tempColNames <- colnames(temp)
						temp <- temp[!duplicated(temp),]
						if (!is.matrix(temp)) {
							temp <- matrix(temp, ncol=length(tempColNames))
							rownames(temp) <- temp[,1]
							colnames(temp) <- tempColNames
						}
					}
					if (dim(temp)[2] > 1) {
						tempColNames <- colnames(temp)[2:dim(temp)[2]]
						tempRowNames <- rownames(temp)
						temp <- as.matrix(temp[,2:dim(temp)[2]])
						colnames(temp) <- tempColNames
						rownames(temp) <- tempRowNames
					}
  					.drawHTMLtable(temp, outFile, tableName=tableNames[i], tableLink=paste('h-', i, sep=''), catType=attr[i], species=getAnnLib(gAList[[1]]), lastRowLink=TRUE, highlightLastRow=FALSE, topCat=0, IDCols=2)
				} else {
					#generate genes in concept table
					tempGenes <- unlist(getGenesInCategory(gAList[[indexM[a,2]]])[rownames(dataMatrix)[indexM[a,1]]])
					tempGeneInput <- getGeneInput(gAList[[indexM[a,2]]])
					temp <- as.matrix(tempGeneInput[tempGeneInput[,1] %in% tempGenes,])
					rownames(temp) <- temp[,1] 
					if (dim(temp)[1] > 1) {
						tempColNames <- colnames(temp)
						temp <- temp[!duplicated(temp),]
						if (!is.matrix(temp)) {
							temp <- matrix(temp, ncol=length(tempColNames))
							rownames(temp) <- temp[,1]
							colnames(temp) <- tempColNames
						}
					}
					if (dim(temp)[2] > 1) {
						tempColNames <- colnames(temp)[2:dim(temp)[2]]
						tempRowNames <- rownames(temp)
						temp <- matrix(temp[,2:dim(temp)[2]], ncol=length(tempColNames))
						colnames(temp) <- tempColNames
						rownames(temp) <- tempRowNames
					}
					#### generate a hyperlink by table name based on catType
					.drawHTMLtable(temp, outFile, tableName=tableNames[i], tableLink=paste('h-', i, sep=''), catType=attr[i], species=getAnnLib(gAList[[1]]), lastRowLink=TRUE, highlightLastRow=FALSE, topCat=0, IDCols=2)
				}
            } else {
				.drawHTMLtable(dataMatrix, outFile, tableName=tableNames[i], tableLink=paste('h-', i, sep=''), catType=attr[i], species=annLib, matrixOfHeatmap=matrixOfHeatmap, topCat=max(showCats), displayText=TRUE)
			} 
		} else {
			if (!is.null(matrixOfHeatmap) & is.numeric(showCats)) {
				temp <- matrixOfHeatmap[,(i-1)]
				drawCats <- names(sort(temp))[showCats]
			} else drawCats <- showCats
			drawCats <- drawCats[drawCats %in% rownames(getEnrichmentInfo(gAList[[i-1]]))]
			if (!is.null(drawCats)) {
				png(filename=paste(tableNames[i], '_', catType, '.png', sep=''),width=1000, height=1000)
				if (length(colorValueColumn) > 1) geneAnswersConceptNet(gAList[[i-1]], centroidSize='pvalue', colorValueColumn = colorValueColumn[i-1], output='fixed', showCats=drawCats, catTerm=catTerm, geneSymbol=TRUE)
				else geneAnswersConceptNet(gAList[[i-1]], centroidSize='pvalue', colorValueColumn = colorValueColumn, output='fixed', showCats=drawCats, catTerm=catTerm, geneSymbol=TRUE)
				dev.off()
				cat(paste('<H2 align=center><font face="courier" size="2"><A name="', paste('h-', i, sep=''), '">', tableNames[i], "</a></font></H2>", sep=''), file = outFile, sep = "\n") 
				cat('<center><IMG src="', paste(tableNames[i], '_', catType, '.png', sep=''), '"></center>\n', file = outFile, sep="")
			} else {
				print('Given categories are not statistical significant!!! No category is selected!')
				cat(paste('<H2 align=center><font face="courier" size="2"><A name="', paste('h-', i, sep=''), '">', tableNames[i], "</a></font></H2>", sep=''), file = outFile, sep = "\n")
				cat('<p style="font-family:courier;text-align:center;color:red">Given categories are not statistical significant!!!!</p>', file = outFile, sep = "\n")
			}
			
		}
		cat('<a HREF="#h-1"><p style="font-family:courier;text-align:right;font-size:11px">To Concepts-Genes Table</p></a>\n<br> <br /><br> <br />\n',file = outFile, sep = "")
	}
	
	cat('</body>', "</html>", sep = "\n", file = outFile)
	close(outFile)
	print(paste(fileName, 'is generated at', getwd()))
}